# Generated by Django 3.2.7 on 2021-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('link_ativo', models.BooleanField(default=True)),
                ('ordem_link', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem do Links')),
            ],
        ),
    ]
